depot/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  get 'store/index'
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

depot/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

depot/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

depot/app/models/product.rb
class Product < ApplicationRecord
  audited
  has_many :line_items

  validates :title, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with:
      %r{\.(gif|jpg|png)\z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
      }

    before_destroy :ensure_not_referenced_by_any_line_item

    private
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      unless line_items.empty?
        errors.add(:base, 'No se puede eliminar hay items que están utilizando el producto')
        throw :abort
      end
    end
end

depot/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Se ha eliinado correctamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

depot/app/controllers/concerns/current_cart.rb
module CurrentCart
  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
        @cart = Cart.create
        session[:cart_id] = @cart.id
  end
end

depot/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: "Item agregado correctamente." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

depot/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

depot/app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @products = Product.order(:title)
  end
end

depot/app/helpers/carts_helper.rb
module CartsHelper
end

depot/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot/app/helpers/products_helper.rb
module ProductsHelper
end

depot/app/helpers/store_helper.rb
module StoreHelper
end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'shared/header' %>
  <body>
    <%= render 'shared/menu' %>
      <div class="container-fluid">
        <div class="row">
          <nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3 sidebar-sticky">
            </div>
          </nav>
          <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="bg-light p-5 rounded <%= controller.controller_name %>">
              <%= yield %>
            </div>
          </main>
        </div>
      </div>
  </body>
</html>

depot/app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

depot/app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

depot/app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

depot/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, 'Título', class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, 'Descripción', class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :image_url, 'Imagen', class: 'form-label'%>
    <%= form.text_field :image_url, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :price, 'Precio', class: 'form-label' %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

depot/app/views/products/edit.html.erb
<div class="card">
  <div class="card-header">
    Editando Producto
    <span class="badge bg-secondary">Id: <%= @product.id %></span>
  </div>
  <div class="card-body">
    <%= render 'form', product: @product %>
  </div>
  <div class="card-footer">
    <%= link_to 'Mostrar', @product %> |
    <%= link_to 'Regresar', products_path %>
  </div>
</div>

depot/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    Productos
  </div>
  <div class="card-body">
    <table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Descripción</th>
      <th>Imagen</th>
      <th>Precio</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('table-primary', '') %>">
        <td><%= product.title %></td>
        <td><%= sanitize(product.description) %></td>
        <td><%= product.image_url %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Mostrar', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Borrar', product, method: :delete, data: { confirm: 'Seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
  <div class="card-footer">
    <%= link_to 'Nuevo Producto', new_product_path %>
  </div>
</div>

depot/app/views/products/new.html.erb
<div class="card">
  <div class="card-header">
    Nuevo Producto
  </div>
  <div class="card-body">
    <%= render 'form', product: @product %>
  </div>
  <div class="card-footer">
    <%= link_to 'Regresar', products_path %>
  </div>
</div>

depot/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Regresar', products_path %>

depot/app/views/shared/_header.html.erb
<head>
  <title>La Ventecita</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

depot/app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark mb-4 bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">La Ventecita</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to 'Inicio', '/', class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Productos', products_path, class: 'nav-link active' %>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, current_user, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to "Salir", destroy_user_session_path, method: 'delete', class: 'nav-link active' %>
          </li>
          <% else %>
            <%= link_to "Iniciar Sesión", new_user_session_path, class: 'nav-link active' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

depot/app/views/store/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<main>

  <section class="py-1 text-center container">
    <div class="row py-lg-1">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Productos Disponibles</h1>
        <p class="lead text-muted">Compre con tranquilidad, el día de pago le hacemos la cuenta.</p>
        <p>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @products.each do |product| %>
          <div class="col">
            <div class="card shadow-sm border-primary">
              <%= image_tag(product.image_url, width: "100%" , height: "225" , class: "bd-placeholder-img card-img-top"
                ) %>
                <div class="card-body">
                  <p class="card-text">
                  <h3>
                    <%= product.title %>
                  </h3>
                  <%= sanitize(product.description) %>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= button_to 'Agregar', line_items_path(product_id: product), class: "btn btn-sm btn-outline-primary" %>
                      </div>
                      <small class="text-muted">
                        <%= sprintf("C$%0.02f", product.price) %>
                      </small>
                    </div>
                </div>
            </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</main>