library/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  root 'books#index', as: 'books_index'
  get 'books/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

library/app/models/book.rb
class Book < ApplicationRecord
  audited
  validates :title, presence: true
  validates :title, uniqueness: true
end

library/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :category, :year)
    end
end

library/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

library/app/helpers/application_helper.rb
module ApplicationHelper
end

library/app/helpers/books_helper.rb
module BooksHelper
end

library/app/helpers/users_helper.rb
module UsersHelper
end

library/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :category, class: 'form-label' %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :year, class: 'form-label' %>
    <%= form.number_field :year, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

library/app/views/books/edit.html.erb
<div class="card">
  <div class="card-header">
    Editing Book
  </div>
  <div class="card-body">
    <%= render 'form', book: @book %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', @book, class: 'label label-primary' %> |
    <%= link_to 'Back', books_path, class: 'label label-primary' %>
  </div>
</div>

library/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="page-header">
    <h1>Book</h1>
  </div>
</div><div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Category</th>
        <th>Year</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.category %></td>
          <td><%= book.year %></td>
          <td class="text-center">
            <%= link_to "Show", book, class: 'label label-info'%>
            <%= link_to "Edit", edit_book_path(book), class: 'label label-success'%>
            <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'label label-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="btn btn-outline-primary">
  <%= link_to 'New Book', new_book_path, :class => "btn-xs" %>
</div>

library/app/views/books/new.html.erb
<div class="card">
  <div class="card-header">
    New Book
  </div>
  <div class="card-body">
    <%= render 'form', book: @book %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', books_path %>
  </div>
</div>

library/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
  <div class="card-header">
    <div class="jumbotron">
      <span class="label label-primary"> Last update <%= @book.updated_at.strftime("%b %d, %Y") %></span>
    </div>
  </div>
  <div class="card-body">
    <div class="panel-body">
      <p>
        <strong>Title:</strong>
        <%= @book.title %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= @book.category %>
      </p>

      <p>
        <strong>Year:</strong>
        <%= @book.year %>
      </p>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Edit', edit_book_path(@book), class: 'label label-primary' %> |
    <%= link_to 'Back', books_path, class: 'label label-primary' %>
  </div>
</div>

library/app/views/shared/_header.html.erb
<head>
  <title>Library</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

library/app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark mb-4 bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to 'List Books', books_path, class: 'nav-link active' %>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, current_user, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to "Exit", destroy_user_session_path, method: 'delete', class: 'nav-link active' %>
          </li>
          <% else %>
            <%= link_to "Sign up", new_user_session_path, class: 'nav-link active' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

library/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

library/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

library/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

library/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

library/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>